name: Build and Release CU2CL

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make cmake wget

      - name: Run Installation Script
        run: |
          chmod +x install.sh
          ./install.sh

      - name: Test Built Binary
        run: |
          # Verify the cu2cl-tool binary exists and outputs version info.
          ./cu2cl-build/cu2cl-tool --version

      - name: Create Release Tag
        if: github.event_name == 'push'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Use the run number to form a unique version tag. Adjust as needed.
          tag_name: "v${{ github.run_number }}"
          release_name: "Release v${{ github.run_number }}"
          body: "Automated release generated by GitHub Actions."
          draft: false
          prerelease: false
