name: Build CU2CL

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make cmake wget

      - name: Run Installation Script
        run: |
          chmod +x install.sh
          ./install.sh

      - name: Test Built Binary
        run: |
          # Check that the cu2cl-tool binary exists and outputs version info
          ./cu2cl-build/cu2cl-tool --version
